import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { extname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getStableApps, TOOLBOX_RELEASE } from '../packages/app-manifest/manifest.js'

const root = fileURLToPath(new URL('../', import.meta.url))
const outputArg = process.argv[2] ?? '-'

function kb(bytes) {
  return (bytes / 1024).toFixed(1)
}

function measure(app) {
  const assets = join(root, 'apps', app.id, 'dist', 'assets')
  let jsRaw = 0
  let jsGzip = 0
  let cssRaw = 0
  let cssGzip = 0
  let largest = { name: '-', gzip: 0 }
  let count = 0
  try {
    for (const entry of readdirSync(assets)) {
      const ext = extname(entry)
      if (ext !== '.js' && ext !== '.css') continue
      const raw = readFileSync(join(assets, entry))
      const gz = gzipSync(raw, { level: 9 }).length
      count += 1
      if (ext === '.js') {
        jsRaw += raw.length
        jsGzip += gz
      } else {
        cssRaw += raw.length
        cssGzip += gz
      }
      if (gz > largest.gzip) largest = { name: entry, gzip: gz }
    }
  } catch {
    // dist missing; report zeros so the run still documents the gap
  }
  return { count, jsRaw, jsGzip, cssRaw, cssGzip, largest }
}

const rows = getStableApps().map((app) => ({ app, ...measure(app) }))
const totalGzip = rows.reduce((sum, row) => sum + row.jsGzip + row.cssGzip, 0)

const lines = [
  `# Performance baseline`,
  '',
  `> Generated by \`node scripts/measure-perf.mjs docs/PERFORMANCE.md\` against built`,
  `> \`dist/assets\` at ${TOOLBOX_RELEASE}. Sizes are raw / gzip(klevel 9); the largest`,
  `> column is the biggest single gzip asset. Update this file when a change`,
  `> intentionally shifts the numbers and say so in the commit message.`,
  '',
  '| App | JS files | JS raw | JS gzip | CSS raw | CSS gzip | Largest gzip asset |',
  '|---|---:|---:|---:|---:|---:|---|',
]
for (const row of rows) {
  lines.push(
    `| ${row.app.name} | ${row.count} | ${kb(row.jsRaw)}k | ${kb(row.jsGzip)}k | ${kb(row.cssRaw)}k | ${kb(row.cssGzip)}k | ${row.largest.name} (${kb(row.largest.gzip)}k) |`,
  )
}
lines.push(`| **Total** | | | **${kb(totalGzip)}k gzip** | | | |`)
lines.push('')

const markdown = lines.join('\n')
if (outputArg === '-') {
  process.stdout.write(markdown)
} else {
  writeFileSync(resolve(root, outputArg), markdown)
  console.log(`[perf] wrote ${outputArg}`)
}
